// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcbjgzthuciqzrcldmey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjYmpnenRodWNpcXpyY2xkbWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTUzMTUsImV4cCI6MjA2MDYzMTMxNX0.0-k4RimU9ZDYkfrcMirAROvllc7894IugFDuFDpdzNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);